language: php

services:
  - mysql

matrix:
  include:
    - php: 7.1
      env: DB=MYSQL RECIPE_VERSION=4.3.0 PHPUNIT_TEST=1 PHPUNIT_COVERAGE_TEST=1 SS_DATABASE_USERNAME="root" SS_DATABASE_PASSWORD="" SS_DATABASE_SERVER="127.0.0.1" SS_DATABASE_CHOOSE_NAME="true" SS_SQLITE_DATABASE_PATH=":memory:" UNIT_TESTS_RUNNING="true" flush="all"
    - php: 7.2
      env: DB=MYSQL RECIPE_VERSION=4.4.0 PHPUNIT_TEST=1 PHPUNIT_COVERAGE_TEST=1 SS_DATABASE_USERNAME="root" SS_DATABASE_PASSWORD="" SS_DATABASE_SERVER="127.0.0.1" SS_DATABASE_CHOOSE_NAME="true" SS_SQLITE_DATABASE_PATH=":memory:" UNIT_TESTS_RUNNING="true" flush="all"
    - php: 7.3
      env: DB=MYSQL RECIPE_VERSION=4.5.0 PHPUNIT_TEST=1 PHPUNIT_COVERAGE_TEST=1 SS_DATABASE_USERNAME="root" SS_DATABASE_PASSWORD="" SS_DATABASE_SERVER="127.0.0.1" SS_DATABASE_CHOOSE_NAME="true" SS_SQLITE_DATABASE_PATH=":memory:" UNIT_TESTS_RUNNING="true" flush="all"

before_script:
  - phpenv rehash
  - phpenv config-rm xdebug.ini

  - composer validate
  - composer require --no-update silverstripe/recipe-cms:"$RECIPE_VERSION"
  - if [[ $DB == PGSQL ]]; then composer require --no-update silverstripe/postgresql:2.1.x-dev; fi
  - composer install --prefer-source --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile

script:
  - if [[ $PHPUNIT_TEST ]]; then vendor/bin/phpunit; fi
  - if [[ $PHPUNIT_COVERAGE_TEST ]]; then phpdbg -qrr vendor/bin/phpunit --coverage-clover=coverage.xml; fi
  - if [[ $PHPCS_TEST ]]; then vendor/bin/phpcs src/ tests/ *.php; fi

after_success:
  - if [[ $PHPUNIT_COVERAGE_TEST ]]; then bash <(curl -s https://codecov.io/bash) -f coverage.xml -F php; fi
